[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamic-tools"
version = "0.1.0"
description = "Dynamic loading test tools for Strands Agent"
authors = [{ name="Meet Mavani" }]
dependencies = []

[tool.setuptools]
packages = ["strands-tools"]
